--- #YAML:1.0
name:                WWW-OpenSearch
version:             0.10_02
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Data::Page:                    2
    Encode:                        0
    LWP:                           5.6
    Test::More:                    0.32
    URI:                           0
    URI::Template:                 0
    XML::Feed:                     0.08
    XML::LibXML:                   1.58
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
