# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-OpenSearch
version:      0.07
version_from: lib/WWW/OpenSearch.pm
installdirs:  site
requires:
    Data::Page:                    2
    Encode:                        0
    LWP:                           5.6
    Test::More:                    0.32
    URI:                           0
    XML::Feed:                     0.08
    XML::LibXML:                   1.58

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
